name: Reusable - Markdown lint check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  markdown-lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install mardkdownlint
        run: npm install markdownlint-cli@0.43.0

      - name: Run markdownlint
        run: |
          markdownlint -c .markdownlint.yml -p .gitignore **/*.md -i licenses/licenses.md
